### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by robmarkcole** [opendatacube/docker-images#13]
Running with the recommended `run` command I get:
```
The Jupyter Notebook is running at: http://89b4a244c508:8888/?token=...
```
but am unable to access on `localhost:8888`. What should I be doing here?
Thanks

**Comment by alexgleith** [comment]
Hi Rob

Good pickup, the command should be this:

```
docker run \
    --rm \
    -p 8888:8888 \
    opendatacube/jupyter \
    jupyter notebook --ip="*" --NotebookApp.token='secretpassword'
```

I'll update the documentation!

A quick note to say that using Docker Compose is a tidier way to do this ;-)

**Comment by robmarkcole** [comment]
Many thanks
