### ISSUE TITLE
Re-designing this repository

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/docker-images#5]
Hi all

I'm hoping to take over this repo to include a number of downstream Docker images based on the [datacube-core image](https://hub.docker.com/r/opendatacube/datacube-core/) (which builds from the [datacube-core repo](https://github.com/opendatacube/datacube-core)).

A recommended structure is something like:

- Root folder includes Makefile to do test builds and readme and license files
  - Sub folders for docker images, i.e., Jupyter, JupyterHub, WMS, WCS, etc...

Each image should be based on the ODC core image, where appropriate.

What do we think?

**Comment by rtaib** [comment]
I agree with your suggestions. The current structure/dockerfiles were established some time ago and have become obsolete in part because of conda being dropped, and because of the wider discussion now on organising docker images for various purposes.

**Comment by alexgleith** [comment]
Ok, so I'm going to push to take this over if I don't get any dissent soon. It's been a bit over a week and the new PR and this issue only have one comment between them.

Hoping to get the dea-dashboard docker image in here next.

**Comment by mpaget** [comment]
@alexgleith go for it. I'm not necessarily up with the details but I'm all for re-use and update of previous efforts.

**Comment by alexgleith** [comment]
Cool. Well I've got the permissions now, so I'll get started ;-)
